### ISSUE TITLE
[BUG] مشکل در دریافت وب‌هوک

### ISSUE THREAD

**Issue by Ilaprgg2** [marzneshin/marzneshin#633]
### Current Behavior

هیچ دیتایی به ادرس وب هوک ارسال نمیشه.

همچنین وقتی که یوزر جدید میسازم یا یوزر رو حذف میکنم این خطا رو در لاگ مرزنشین میبینم:

```
marzneshin-1  | Task exception was never retrieved
marzneshin-1  | future: <Task finished name='Task-36' coro=<user_created() done, defined at /app/app/utils/report.py:52> exception=AttributeError("'UserResponse' object has no attribute 'services'")>
marzneshin-1  | Traceback (most recent call last):
marzneshin-1  |   File "/app/app/utils/report.py", line 60, in user_created
marzneshin-1  |     services=user.services,
marzneshin-1  |              ^^^^^^^^^^^^^
marzneshin-1  |   File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 811, in __getattr__
marzneshin-1  |     raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
marzneshin-1  | AttributeError: 'UserResponse' object has no attribute 'services'. Did you mean: 'service_ids'?
marzneshin-1  | INFO:     172.104.241.86:58428 - "POST /api/users HTTP/1.1" 200 OK
```

```
marzneshin-1  | INFO:     @app.routes.user: User None deleted
marzneshin-1  | Task exception was never retrieved
marzneshin-1  | future: <Task finished name='Task-52' coro=<user_deleted() done, defined at /app/app/utils/report.py:94> exception=1 validation error for UserDeleted
marzneshin-1  | username
marzneshin-1  |   Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
marzneshin-1  |     For further information visit https://errors.pydantic.dev/2.7/v/string_type>
marzneshin-1  | Traceback (most recent call last):
marzneshin-1  |   File "/app/app/utils/report.py", line 100, in user_deleted
marzneshin-1  |     UserDeleted(
marzneshin-1  |   File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 176, in __init__
marzneshin-1  |     self.__pydantic_validator__.validate_python(data, self_instance=self)
marzneshin-1  | pydantic_core._pydantic_core.ValidationError: 1 validation error for UserDeleted
marzneshin-1  | username
marzneshin-1  |   Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
marzneshin-1  |     For further information visit https://errors.pydantic.dev/2.7/v/string_type
```

### Environment

OS:
ubuntu 22

Marzneshin Version: v0.6.2

sqlite and mariadb

**Comment by thissmeme** [comment]
منم همین مشکلو دارم

**Comment by khodedawsh** [comment]
چه نسخه‌ای @thissmeme و دقیقا چه مشکلی؟
