### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by LonUp** [marzneshin/marzneshin#647]
### Current Behavior

When deleting a user either through the panel or the Mirza bot, an error occurs in all three types of databases.

After the user is deleted and this error appears, several issues arise:

```
marzneshin-1  | INFO:     @app.routes.user: User None deleted
marzneshin-1  | Task exception was never retrieved
marzneshin-1  | future: <Task finished name='Task-79' coro=<user_deleted() done, defined at /app/app/utils/report.py:94> exception=1 validation error for UserDeleted
marzneshin-1  | username
marzneshin-1  |   Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
marzneshin-1  |     For further information visit https://errors.pydantic.dev/2.7/v/string_type>
marzneshin-1  | Traceback (most recent call last):
marzneshin-1  |   File "/app/app/utils/report.py", line 100, in user_deleted
marzneshin-1  |     UserDeleted(
marzneshin-1  |   File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 176, in __init__
marzneshin-1  |     self.__pydantic_validator__.validate_python(data, self_instance=self)
marzneshin-1  | pydantic_core._pydantic_core.ValidationError: 1 validation error for UserDeleted
marzneshin-1  | username
marzneshin-1  |   Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
marzneshin-1  |     For further information visit https://errors.pydantic.dev/2.7/v/string_type
```

```
marznode-1    | Application error
marznode-1    | Traceback (most recent call last):
marznode-1    |   File "/usr/local/lib/python3.12/site-packages/grpclib/server.py", line 446, in request_handler
marznode-1    |     await method_func(stream)
marznode-1    |   File "/app/marznode/service/service.py", line 134, in RepopulateUsers
marznode-1    |     await self._remove_user(storage_user, storage_user.inbounds)
marznode-1    |   File "/app/marznode/service/service.py", line 62, in _remove_user
marznode-1    |     await backend.remove_user(user, inbound)
marznode-1    |   File "/app/marznode/backends/hysteria2/hysteria2_backend.py", line 103, in remove_user
marznode-1    |     self._users.pop(user.key)
marznode-1    | KeyError: '709052593c8c34a6bee3e4e29904d507'
marzneshin-1  | INFO:     @app.routes.user: User None deleted
marzneshin-1  | Task exception was never retrieved
marzneshin-1  | future: <Task finished name='Task-1841' coro=<user_deleted() done, defined at /app/app/utils/report.py:94> exception=1 validation error for UserDeleted
marzneshin-1  | username
marzneshin-1  |   Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
marzneshin-1  |     For further information visit https://errors.pydantic.dev/2.7/v/string_type>
marzneshin-1  | Traceback (most recent call last):
marzneshin-1  |   File "/app/app/utils/report.py", line 100, in user_deleted
marzneshin-1  |     UserDeleted(
marzneshin-1  |   File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 176, in __init__
marzneshin-1  |     self.__pydantic_validator__.validate_python(data, self_instance=self)
marzneshin-1  | pydantic_core._pydantic_core.ValidationError: 1 validation error for UserDeleted
marzneshin-1  | username
marzneshin-1  |   Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
marzneshin-1  |     For further information visit https://errors.pydantic.dev/2.7/v/string_type
marzneshin-1  | INFO:     108.162.227.6:42428 - "DELETE /api/users/vip_4f70 HTTP/1.1" 200 OK
marznode-1    | Application error
marznode-1    | Traceback (most recent call last):
marznode-1    |   File "/usr/local/lib/python3.12/site-packages/grpclib/server.py", line 446, in request_handler
marznode-1    |     await method_func(stream)
marznode-1    |   File "/app/marznode/service/service.py", line 103, in SyncUsers
marznode-1    |     await self._update_user(user_data)
marznode-1    |   File "/app/marznode/service/service.py", line 82, in _update_user
marznode-1    |     await self._remove_user(storage_user, storage_user.inbounds)
marznode-1    |   File "/app/marznode/service/service.py", line 62, in _remove_user
marznode-1    |     await backend.remove_user(user, inbound)
marznode-1    |   File "/app/marznode/backends/hysteria2/hysteria2_backend.py", line 103, in remove_user
marznode-1    |     self._users.pop(user.key)
marznode-1    | KeyError: 'a5c2bd04dc6247de1bfc2b897e58ed14'

```
Disruptions in the communication between the main panel and the node.
Problems creating new users. Specifically, when a new user is created, the user link returns an EOF error. To resolve this, the panel or the MarzNode service must be restarted for the user to successfully connect.

### Expected Behavior

When deleting a user from the panel or the Mirza bot, the user should be completely removed without any errors. The panel should maintain seamless communication with the node, and new users should be created successfully without any EOF errors. Restarting the panel or MarzNode service should not be necessary for new users to connect.

### Steps To Reproduce

Log in to the panel or use the Mirza bot.
Select a user and delete them from the panel or via the bot.
Observe the error that occurs during the deletion process.
Try to create a new user after the error.
Notice that the new user's link generates an EOF error and requires restarting the panel or MarzNode for the connection to work.

### Environment

OS: ubuntu24

Browsers: brave latest

Version: marzneshin latest and nightly

**Comment by khodedawsh** [comment]
مشکل با هیستریا روی نود بوده قبلا فیکس شده، ربطی به اینجا نداره در هر صورت
